[package]
name = "borker-rs"
version = "0.1.0"
authors = ["Aiden McClelland <gagglehoof@gmail.com>"]
edition = "2018"

[lib]
name = "borker_lib"
path = "src/lib.rs"

[[bin]]
name = "borker_cli"
path = "src/main.rs"

[dependencies]
base58 = "0.1.0"
failure = "0.1.3"
libsecp256k1 = "0.1.14"
rand = { version = "0.6", features = ["stdweb"] }
ripemd160 = "0.8.0"
sha2 = "0.8.0"