[package]
name = "borker-rs"
version = "0.1.0"
authors = ["Aiden McClelland <gagglehoof@gmail.com>"]
edition = "2018"

[dependencies]
bitcoin = "0.15"
bitcoinrpc = { git = "https://github.com/DR-BoneZ/rust-bitcoin-rpc", features = ["doge"] }