[package]
name = "borker-rs"
version = "0.1.0"
authors = ["Aiden McClelland <gagglehoof@gmail.com>"]
edition = "2018"

[lib]
name = "borker_lib"
path = "src/lib.rs"

[[bin]]
name = "borker_cli"
path = "src/main.rs"

[dependencies]
bitcoin = "0.15"
bitcoinrpc = { git = "https://github.com/DR-BoneZ/rust-bitcoin-rpc", features = ["doge"] }
failure = "0.1.3"
rand = "0.6"
sha2 = "0.8.0"